/**
 * symbols
 */

export const ANTDVX_SYMBOLS = {
  // Services
  AUTH_SERVICE: Symbol.for('AUTH_SERVICE'),
  AUTH_SERVICE_CONFIG: Symbol.for('AUTH_SERVICE_CONFIG'),

  HTTP_SERVICE: Symbol.for('HTTP_SERVICE'),
  HTTP_SERVICE_CONFIG: Symbol.for('HTTP_SERVICE_CONFIG'),

  SESSION_SERVICE: Symbol.for('SESSION_SERVICE'),
  SESSION_SERVICE_CONFIG: Symbol.for('SESSION_SERVICE_CONFIG'),

  STORAGE_SERVICE: Symbol.for('STORAGE_SERVICE'),
  STORAGE_SERVICE_IDENTIFICATION: Symbol.for('STORAGE_SERVICE_IDENTIFICATION')
};
