/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { LoginInParm } from '../models';
// @ts-ignore
import { LoginOutParm } from '../models';
// @ts-ignore
import { ResultDataBoolean } from '../models';
// @ts-ignore
import { ResultDataLoginInEntity } from '../models';
/**
 * LoginApi - axios parameter creator
 * @export
 */
export const LoginApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 用户登陆
         * @param {LoginInParm} loginInParm 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginIn: async (loginInParm: LoginInParm, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginInParm' is not null or undefined
            assertParamExists('loginIn', 'loginInParm', loginInParm)
            const localVarPath = `/Login/In`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginInParm, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 用户登出
         * @param {LoginOutParm} [loginOutParm] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginOut: async (loginOutParm?: LoginOutParm, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/Login/Out`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginOutParm, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LoginApi - functional programming interface
 * @export
 */
export const LoginApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LoginApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 用户登陆
         * @param {LoginInParm} loginInParm 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginIn(loginInParm: LoginInParm, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataLoginInEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginIn(loginInParm, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 用户登出
         * @param {LoginOutParm} [loginOutParm] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginOut(loginOutParm?: LoginOutParm, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginOut(loginOutParm, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LoginApi - factory interface
 * @export
 */
export const LoginApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LoginApiFp(configuration)
    return {
        /**
         * 
         * @summary 用户登陆
         * @param {LoginInParm} loginInParm 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginIn(loginInParm: LoginInParm, options?: any): AxiosPromise<ResultDataLoginInEntity> {
            return localVarFp.loginIn(loginInParm, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 用户登出
         * @param {LoginOutParm} [loginOutParm] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginOut(loginOutParm?: LoginOutParm, options?: any): AxiosPromise<ResultDataBoolean> {
            return localVarFp.loginOut(loginOutParm, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for loginIn operation in LoginApi.
 * @export
 * @interface LoginApiLoginInRequest
 */
export interface LoginApiLoginInRequest {
    /**
     * 
     * @type {LoginInParm}
     * @memberof LoginApiLoginIn
     */
    readonly loginInParm: LoginInParm
}

/**
 * Request parameters for loginOut operation in LoginApi.
 * @export
 * @interface LoginApiLoginOutRequest
 */
export interface LoginApiLoginOutRequest {
    /**
     * 
     * @type {LoginOutParm}
     * @memberof LoginApiLoginOut
     */
    readonly loginOutParm?: LoginOutParm
}

/**
 * LoginApi - object-oriented interface
 * @export
 * @class LoginApi
 * @extends {BaseAPI}
 */
export class LoginApi extends BaseAPI {
    /**
     * 
     * @summary 用户登陆
     * @param {LoginApiLoginInRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoginApi
     */
    public loginIn(requestParameters: LoginApiLoginInRequest, options?: any) {
        return LoginApiFp(this.configuration).loginIn(requestParameters.loginInParm, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 用户登出
     * @param {LoginApiLoginOutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoginApi
     */
    public loginOut(requestParameters: LoginApiLoginOutRequest = {}, options?: any) {
        return LoginApiFp(this.configuration).loginOut(requestParameters.loginOutParm, options).then((request) => request(this.axios, this.basePath));
    }
}
