/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { IDsInput } from '../models';
// @ts-ignore
import { PageInputBase } from '../models';
// @ts-ignore
import { ResultDataBoolean } from '../models';
// @ts-ignore
import { ResultDataFileContentResult } from '../models';
// @ts-ignore
import { ResultDataIQueryableStaffingPoolOutput } from '../models';
// @ts-ignore
import { ResultDataListStaffingPoolOutput } from '../models';
// @ts-ignore
import { ResultDataPageResultStaffingPoolOutput } from '../models';
// @ts-ignore
import { ResultDataStaffingPoolOutput } from '../models';
// @ts-ignore
import { StaffingPoolInput } from '../models';
/**
 * StaffingPoolApi - axios parameter creator
 * @export
 */
export const StaffingPoolApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 勾选部分Excel导出
         * @param {IDsInput} [iDsInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolByIDsExport: async (iDsInput?: IDsInput, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/MasterData/StaffingPool/ByIDs/Export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(iDsInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据多个ID查询对象集合
         * @param {IDsInput} [iDsInput] 多个主键
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolByIDsList: async (iDsInput?: IDsInput, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/MasterData/StaffingPool/ByIDs/List`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(iDsInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 删除
         * @param {IDsInput} [iDsInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolDelete: async (iDsInput?: IDsInput, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/MasterData/StaffingPool/Delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(iDsInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 根据ID查询对象
         * @param {string} id 主键
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolIdInfo: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('masterDataStaffingPoolIdInfo', 'id', id)
            const localVarPath = `/MasterData/StaffingPool/{Id}/Info`
                .replace(`{${"Id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Odata 查询
         * @param {string} [filter] $filter
         * @param {string} [apply] $apply
         * @param {string} [orderby] $orderby
         * @param {string} [top] $top
         * @param {string} [skip] $skip
         * @param {string} [select] $select
         * @param {string} [expand] $expand
         * @param {string} [count] $count
         * @param {string} [format] $format
         * @param {string} [skiptoken] $skiptoken
         * @param {string} [deltatoken] $deltatoken
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolOdataAll: async (filter?: string, apply?: string, orderby?: string, top?: string, skip?: string, select?: string, expand?: string, count?: string, format?: string, skiptoken?: string, deltatoken?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/MasterData/StaffingPool/Odata/All`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (apply !== undefined) {
                localVarQueryParameter['apply'] = apply;
            }

            if (orderby !== undefined) {
                localVarQueryParameter['orderby'] = orderby;
            }

            if (top !== undefined) {
                localVarQueryParameter['top'] = top;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }

            if (expand !== undefined) {
                localVarQueryParameter['expand'] = expand;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (skiptoken !== undefined) {
                localVarQueryParameter['skiptoken'] = skiptoken;
            }

            if (deltatoken !== undefined) {
                localVarQueryParameter['deltatoken'] = deltatoken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary [Odata]Excel导出
         * @param {string} [filter] $filter
         * @param {string} [apply] $apply
         * @param {string} [orderby] $orderby
         * @param {string} [top] $top
         * @param {string} [skip] $skip
         * @param {string} [select] $select
         * @param {string} [expand] $expand
         * @param {string} [count] $count
         * @param {string} [format] $format
         * @param {string} [skiptoken] $skiptoken
         * @param {string} [deltatoken] $deltatoken
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolOdataExport: async (filter?: string, apply?: string, orderby?: string, top?: string, skip?: string, select?: string, expand?: string, count?: string, format?: string, skiptoken?: string, deltatoken?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/MasterData/StaffingPool/Odata/Export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (apply !== undefined) {
                localVarQueryParameter['apply'] = apply;
            }

            if (orderby !== undefined) {
                localVarQueryParameter['orderby'] = orderby;
            }

            if (top !== undefined) {
                localVarQueryParameter['top'] = top;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (select !== undefined) {
                localVarQueryParameter['select'] = select;
            }

            if (expand !== undefined) {
                localVarQueryParameter['expand'] = expand;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (skiptoken !== undefined) {
                localVarQueryParameter['skiptoken'] = skiptoken;
            }

            if (deltatoken !== undefined) {
                localVarQueryParameter['deltatoken'] = deltatoken;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 数据库 分页查询
         * @param {PageInputBase} [pageInputBase] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolPageAll: async (pageInputBase?: PageInputBase, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/MasterData/StaffingPool/Page/All`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pageInputBase, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 增加和修改
         * @param {StaffingPoolInput} [staffingPoolInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolSave: async (staffingPoolInput?: StaffingPoolInput, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/MasterData/StaffingPool/Save`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(staffingPoolInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StaffingPoolApi - functional programming interface
 * @export
 */
export const StaffingPoolApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StaffingPoolApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 勾选部分Excel导出
         * @param {IDsInput} [iDsInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolByIDsExport(iDsInput?: IDsInput, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataFileContentResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolByIDsExport(iDsInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 根据多个ID查询对象集合
         * @param {IDsInput} [iDsInput] 多个主键
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolByIDsList(iDsInput?: IDsInput, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataListStaffingPoolOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolByIDsList(iDsInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 删除
         * @param {IDsInput} [iDsInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolDelete(iDsInput?: IDsInput, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolDelete(iDsInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 根据ID查询对象
         * @param {string} id 主键
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolIdInfo(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataStaffingPoolOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolIdInfo(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Odata 查询
         * @param {string} [filter] $filter
         * @param {string} [apply] $apply
         * @param {string} [orderby] $orderby
         * @param {string} [top] $top
         * @param {string} [skip] $skip
         * @param {string} [select] $select
         * @param {string} [expand] $expand
         * @param {string} [count] $count
         * @param {string} [format] $format
         * @param {string} [skiptoken] $skiptoken
         * @param {string} [deltatoken] $deltatoken
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolOdataAll(filter?: string, apply?: string, orderby?: string, top?: string, skip?: string, select?: string, expand?: string, count?: string, format?: string, skiptoken?: string, deltatoken?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataIQueryableStaffingPoolOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolOdataAll(filter, apply, orderby, top, skip, select, expand, count, format, skiptoken, deltatoken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary [Odata]Excel导出
         * @param {string} [filter] $filter
         * @param {string} [apply] $apply
         * @param {string} [orderby] $orderby
         * @param {string} [top] $top
         * @param {string} [skip] $skip
         * @param {string} [select] $select
         * @param {string} [expand] $expand
         * @param {string} [count] $count
         * @param {string} [format] $format
         * @param {string} [skiptoken] $skiptoken
         * @param {string} [deltatoken] $deltatoken
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolOdataExport(filter?: string, apply?: string, orderby?: string, top?: string, skip?: string, select?: string, expand?: string, count?: string, format?: string, skiptoken?: string, deltatoken?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataFileContentResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolOdataExport(filter, apply, orderby, top, skip, select, expand, count, format, skiptoken, deltatoken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 数据库 分页查询
         * @param {PageInputBase} [pageInputBase] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolPageAll(pageInputBase?: PageInputBase, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataPageResultStaffingPoolOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolPageAll(pageInputBase, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 增加和修改
         * @param {StaffingPoolInput} [staffingPoolInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async masterDataStaffingPoolSave(staffingPoolInput?: StaffingPoolInput, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultDataBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.masterDataStaffingPoolSave(staffingPoolInput, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * StaffingPoolApi - factory interface
 * @export
 */
export const StaffingPoolApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StaffingPoolApiFp(configuration)
    return {
        /**
         * 
         * @summary 勾选部分Excel导出
         * @param {IDsInput} [iDsInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolByIDsExport(iDsInput?: IDsInput, options?: any): AxiosPromise<ResultDataFileContentResult> {
            return localVarFp.masterDataStaffingPoolByIDsExport(iDsInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据多个ID查询对象集合
         * @param {IDsInput} [iDsInput] 多个主键
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolByIDsList(iDsInput?: IDsInput, options?: any): AxiosPromise<ResultDataListStaffingPoolOutput> {
            return localVarFp.masterDataStaffingPoolByIDsList(iDsInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 删除
         * @param {IDsInput} [iDsInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolDelete(iDsInput?: IDsInput, options?: any): AxiosPromise<ResultDataBoolean> {
            return localVarFp.masterDataStaffingPoolDelete(iDsInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 根据ID查询对象
         * @param {string} id 主键
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolIdInfo(id: string, options?: any): AxiosPromise<ResultDataStaffingPoolOutput> {
            return localVarFp.masterDataStaffingPoolIdInfo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Odata 查询
         * @param {string} [filter] $filter
         * @param {string} [apply] $apply
         * @param {string} [orderby] $orderby
         * @param {string} [top] $top
         * @param {string} [skip] $skip
         * @param {string} [select] $select
         * @param {string} [expand] $expand
         * @param {string} [count] $count
         * @param {string} [format] $format
         * @param {string} [skiptoken] $skiptoken
         * @param {string} [deltatoken] $deltatoken
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolOdataAll(filter?: string, apply?: string, orderby?: string, top?: string, skip?: string, select?: string, expand?: string, count?: string, format?: string, skiptoken?: string, deltatoken?: string, options?: any): AxiosPromise<ResultDataIQueryableStaffingPoolOutput> {
            return localVarFp.masterDataStaffingPoolOdataAll(filter, apply, orderby, top, skip, select, expand, count, format, skiptoken, deltatoken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary [Odata]Excel导出
         * @param {string} [filter] $filter
         * @param {string} [apply] $apply
         * @param {string} [orderby] $orderby
         * @param {string} [top] $top
         * @param {string} [skip] $skip
         * @param {string} [select] $select
         * @param {string} [expand] $expand
         * @param {string} [count] $count
         * @param {string} [format] $format
         * @param {string} [skiptoken] $skiptoken
         * @param {string} [deltatoken] $deltatoken
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolOdataExport(filter?: string, apply?: string, orderby?: string, top?: string, skip?: string, select?: string, expand?: string, count?: string, format?: string, skiptoken?: string, deltatoken?: string, options?: any): AxiosPromise<ResultDataFileContentResult> {
            return localVarFp.masterDataStaffingPoolOdataExport(filter, apply, orderby, top, skip, select, expand, count, format, skiptoken, deltatoken, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 数据库 分页查询
         * @param {PageInputBase} [pageInputBase] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolPageAll(pageInputBase?: PageInputBase, options?: any): AxiosPromise<ResultDataPageResultStaffingPoolOutput> {
            return localVarFp.masterDataStaffingPoolPageAll(pageInputBase, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 增加和修改
         * @param {StaffingPoolInput} [staffingPoolInput] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        masterDataStaffingPoolSave(staffingPoolInput?: StaffingPoolInput, options?: any): AxiosPromise<ResultDataBoolean> {
            return localVarFp.masterDataStaffingPoolSave(staffingPoolInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for masterDataStaffingPoolByIDsExport operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolByIDsExportRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolByIDsExportRequest {
    /**
     * 
     * @type {IDsInput}
     * @memberof StaffingPoolApiMasterDataStaffingPoolByIDsExport
     */
    readonly iDsInput?: IDsInput
}

/**
 * Request parameters for masterDataStaffingPoolByIDsList operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolByIDsListRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolByIDsListRequest {
    /**
     * 多个主键
     * @type {IDsInput}
     * @memberof StaffingPoolApiMasterDataStaffingPoolByIDsList
     */
    readonly iDsInput?: IDsInput
}

/**
 * Request parameters for masterDataStaffingPoolDelete operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolDeleteRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolDeleteRequest {
    /**
     * 
     * @type {IDsInput}
     * @memberof StaffingPoolApiMasterDataStaffingPoolDelete
     */
    readonly iDsInput?: IDsInput
}

/**
 * Request parameters for masterDataStaffingPoolIdInfo operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolIdInfoRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolIdInfoRequest {
    /**
     * 主键
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolIdInfo
     */
    readonly id: string
}

/**
 * Request parameters for masterDataStaffingPoolOdataAll operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolOdataAllRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolOdataAllRequest {
    /**
     * $filter
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly filter?: string

    /**
     * $apply
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly apply?: string

    /**
     * $orderby
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly orderby?: string

    /**
     * $top
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly top?: string

    /**
     * $skip
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly skip?: string

    /**
     * $select
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly select?: string

    /**
     * $expand
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly expand?: string

    /**
     * $count
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly count?: string

    /**
     * $format
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly format?: string

    /**
     * $skiptoken
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly skiptoken?: string

    /**
     * $deltatoken
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataAll
     */
    readonly deltatoken?: string
}

/**
 * Request parameters for masterDataStaffingPoolOdataExport operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolOdataExportRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolOdataExportRequest {
    /**
     * $filter
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly filter?: string

    /**
     * $apply
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly apply?: string

    /**
     * $orderby
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly orderby?: string

    /**
     * $top
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly top?: string

    /**
     * $skip
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly skip?: string

    /**
     * $select
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly select?: string

    /**
     * $expand
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly expand?: string

    /**
     * $count
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly count?: string

    /**
     * $format
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly format?: string

    /**
     * $skiptoken
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly skiptoken?: string

    /**
     * $deltatoken
     * @type {string}
     * @memberof StaffingPoolApiMasterDataStaffingPoolOdataExport
     */
    readonly deltatoken?: string
}

/**
 * Request parameters for masterDataStaffingPoolPageAll operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolPageAllRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolPageAllRequest {
    /**
     * 
     * @type {PageInputBase}
     * @memberof StaffingPoolApiMasterDataStaffingPoolPageAll
     */
    readonly pageInputBase?: PageInputBase
}

/**
 * Request parameters for masterDataStaffingPoolSave operation in StaffingPoolApi.
 * @export
 * @interface StaffingPoolApiMasterDataStaffingPoolSaveRequest
 */
export interface StaffingPoolApiMasterDataStaffingPoolSaveRequest {
    /**
     * 
     * @type {StaffingPoolInput}
     * @memberof StaffingPoolApiMasterDataStaffingPoolSave
     */
    readonly staffingPoolInput?: StaffingPoolInput
}

/**
 * StaffingPoolApi - object-oriented interface
 * @export
 * @class StaffingPoolApi
 * @extends {BaseAPI}
 */
export class StaffingPoolApi extends BaseAPI {
    /**
     * 
     * @summary 勾选部分Excel导出
     * @param {StaffingPoolApiMasterDataStaffingPoolByIDsExportRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolByIDsExport(requestParameters: StaffingPoolApiMasterDataStaffingPoolByIDsExportRequest = {}, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolByIDsExport(requestParameters.iDsInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 根据多个ID查询对象集合
     * @param {StaffingPoolApiMasterDataStaffingPoolByIDsListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolByIDsList(requestParameters: StaffingPoolApiMasterDataStaffingPoolByIDsListRequest = {}, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolByIDsList(requestParameters.iDsInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 删除
     * @param {StaffingPoolApiMasterDataStaffingPoolDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolDelete(requestParameters: StaffingPoolApiMasterDataStaffingPoolDeleteRequest = {}, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolDelete(requestParameters.iDsInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 根据ID查询对象
     * @param {StaffingPoolApiMasterDataStaffingPoolIdInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolIdInfo(requestParameters: StaffingPoolApiMasterDataStaffingPoolIdInfoRequest, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolIdInfo(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Odata 查询
     * @param {StaffingPoolApiMasterDataStaffingPoolOdataAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolOdataAll(requestParameters: StaffingPoolApiMasterDataStaffingPoolOdataAllRequest = {}, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolOdataAll(requestParameters.filter, requestParameters.apply, requestParameters.orderby, requestParameters.top, requestParameters.skip, requestParameters.select, requestParameters.expand, requestParameters.count, requestParameters.format, requestParameters.skiptoken, requestParameters.deltatoken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary [Odata]Excel导出
     * @param {StaffingPoolApiMasterDataStaffingPoolOdataExportRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolOdataExport(requestParameters: StaffingPoolApiMasterDataStaffingPoolOdataExportRequest = {}, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolOdataExport(requestParameters.filter, requestParameters.apply, requestParameters.orderby, requestParameters.top, requestParameters.skip, requestParameters.select, requestParameters.expand, requestParameters.count, requestParameters.format, requestParameters.skiptoken, requestParameters.deltatoken, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 数据库 分页查询
     * @param {StaffingPoolApiMasterDataStaffingPoolPageAllRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolPageAll(requestParameters: StaffingPoolApiMasterDataStaffingPoolPageAllRequest = {}, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolPageAll(requestParameters.pageInputBase, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 增加和修改
     * @param {StaffingPoolApiMasterDataStaffingPoolSaveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StaffingPoolApi
     */
    public masterDataStaffingPoolSave(requestParameters: StaffingPoolApiMasterDataStaffingPoolSaveRequest = {}, options?: any) {
        return StaffingPoolApiFp(this.configuration).masterDataStaffingPoolSave(requestParameters.staffingPoolInput, options).then((request) => request(this.axios, this.basePath));
    }
}
