/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';

/**
 * 
 * @export
 * @interface AddConfigInput
 */
export interface AddConfigInput {
    /**
     * 名称
     * @type {string}
     * @memberof AddConfigInput
     */
    Name: string;
    /**
     * 编码
     * @type {string}
     * @memberof AddConfigInput
     */
    Code: string;
    /**
     * 属性值
     * @type {string}
     * @memberof AddConfigInput
     */
    Value?: string | null;
    /**
     * 是否是系统参数（Y-是，N-否）
     * @type {string}
     * @memberof AddConfigInput
     */
    SysFlag?: string | null;
    /**
     * 备注
     * @type {string}
     * @memberof AddConfigInput
     */
    Remark?: string | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof AddConfigInput
     */
    Status?: CommonStatus;
    /**
     * 常量所属分类的编码，来自于“常量的分类”字典
     * @type {string}
     * @memberof AddConfigInput
     */
    GroupCode?: string | null;
}


