/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 账号类型<br />&nbsp;普通账号 None = 0<br />&nbsp;管理员 Admin = 1<br />&nbsp;超级管理员 SuperAdmin = 2<br />
 * @export
 * @enum {string}
 */

export enum AdminType {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}



