/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 修改密码
 * @export
 * @interface ChangeUserPasswordParm
 */
export interface ChangeUserPasswordParm {
    /**
     * 账号
     * @type {string}
     * @memberof ChangeUserPasswordParm
     */
    Account?: string | null;
    /**
     * 新密码
     * @type {string}
     * @memberof ChangeUserPasswordParm
     */
    NewPassword: string;
}


