/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Condition } from './condition';

/**
 * 参数配置
 * @export
 * @interface ConfigPageInput
 */
export interface ConfigPageInput {
    /**
     * 当前页码
     * @type {number}
     * @memberof ConfigPageInput
     */
    PageNo?: number;
    /**
     * 页码容量
     * @type {number}
     * @memberof ConfigPageInput
     */
    PageSize?: number;
    /**
     * 搜索值
     * @type {string}
     * @memberof ConfigPageInput
     */
    SearchValue?: string | null;
    /**
     * 搜索开始时间
     * @type {string}
     * @memberof ConfigPageInput
     */
    SearchBeginTime?: string | null;
    /**
     * 搜索结束时间
     * @type {string}
     * @memberof ConfigPageInput
     */
    SearchEndTime?: string | null;
    /**
     * 排序字段
     * @type {string}
     * @memberof ConfigPageInput
     */
    SortField?: string | null;
    /**
     * 排序方法,默认升序,否则降序(配合antd前端,约定参数为 Ascend,Dscend)
     * @type {string}
     * @memberof ConfigPageInput
     */
    SortOrder?: string | null;
    /**
     * 降序排序(约定参数 ascend,dscend)默认dscend
     * @type {string}
     * @memberof ConfigPageInput
     */
    DescStr?: string | null;
    /**
     * 复杂查询条件
     * @type {Array<Condition>}
     * @memberof ConfigPageInput
     */
    SearchParameters?: Array<Condition> | null;
    /**
     * 名称
     * @type {string}
     * @memberof ConfigPageInput
     */
    Name?: string | null;
    /**
     * 编码
     * @type {string}
     * @memberof ConfigPageInput
     */
    Code?: string | null;
    /**
     * 常量所属分类的编码，来自于“常量的分类”字典
     * @type {string}
     * @memberof ConfigPageInput
     */
    GroupCode?: string | null;
}


