/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 登陆类型<br />&nbsp;登陆 LOGIN = 0<br />&nbsp;登出 LOGOUT = 1<br />&nbsp;注册 REGISTER = 2<br />&nbsp;改密 CHANGEPASSWORD = 3<br />&nbsp;授权登陆 AUTHORIZEDLOGIN = 4<br />
 * @export
 * @enum {string}
 */

export enum LoginType {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4
}



