/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 登录模型
 * @export
 * @interface LoginInParm
 */
export interface LoginInParm {
    /**
     * 登录账户
     * @type {string}
     * @memberof LoginInParm
     */
    Account: string;
    /**
     * 登录密码
     * @type {string}
     * @memberof LoginInParm
     */
    Password: string;
}


