/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SendMessageTypeEnum } from './send-message-type-enum';

/**
 * 发送给一些人
 * @export
 * @interface MessageUsersInput
 */
export interface MessageUsersInput {
    /**
     * 消息标题
     * @type {string}
     * @memberof MessageUsersInput
     */
    Title?: string | null;
    /**
     * 消息内容
     * @type {string}
     * @memberof MessageUsersInput
     */
    Message?: string | null;
    /**
     * 
     * @type {SendMessageTypeEnum}
     * @memberof MessageUsersInput
     */
    MessageType?: SendMessageTypeEnum;
    /**
     * 人员
     * @type {Array<string>}
     * @memberof MessageUsersInput
     */
    userCodes?: Array<string> | null;
}


