/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NoticeUserStatus } from './notice-user-status';

/**
 * 通知公告用户状态
 * @export
 * @interface NoticeUserStatusInput
 */
export interface NoticeUserStatusInput {
    /**
     * 
     * @type {NoticeUserStatus}
     * @memberof NoticeUserStatusInput
     */
    NoticeUserStatus?: NoticeUserStatus;
}


