/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 通知公告用户状态<br />&nbsp;未读 UNREAD = 0<br />&nbsp;已读 READ = 1<br />&nbsp;暂不通知 NONOTICE = 2<br />
 * @export
 * @enum {string}
 */

export enum NoticeUserStatus {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}



