/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PhaseObject
 */
export interface PhaseObject {
    /**
     * 
     * @type {string}
     * @memberof PhaseObject
     */
    PhaseCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PhaseObject
     */
    PhaseStart?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PhaseObject
     */
    PhaseEnd?: string | null;
}


