/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 输入模型
 * @export
 * @interface PositionInput
 */
export interface PositionInput {
    /**
     * Id主键
     * @type {number}
     * @memberof PositionInput
     */
    ID?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PositionInput
     */
    ProjectNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PositionInput
     */
    PositionCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PositionInput
     */
    PositionName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PositionInput
     */
    CompanyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PositionInput
     */
    TypeOfPosition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PositionInput
     */
    JobCategory?: string | null;
    /**
     * 备用字段1
     * @type {string}
     * @memberof PositionInput
     */
    Reserved1?: string | null;
}


