/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ProjectSchedule
 * @export
 * @interface ProjectSchedule
 */
export interface ProjectSchedule {
    /**
     * 备用字段1
     * @type {string}
     * @memberof ProjectSchedule
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof ProjectSchedule
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof ProjectSchedule
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof ProjectSchedule
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof ProjectSchedule
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof ProjectSchedule
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof ProjectSchedule
     */
    CreatorName?: string | null;
    /**
     * 主键Id
     * @type {number}
     * @memberof ProjectSchedule
     */
    ID?: number;
    /**
     * 项目编号
     * @type {string}
     * @memberof ProjectSchedule
     */
    ProjectNo?: string | null;
    /**
     * 排列序列号 1-6 前台固定
     * @type {number}
     * @memberof ProjectSchedule
     */
    PhaseSequenceNo?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectSchedule
     */
    PhaseCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSchedule
     */
    PhaseStart?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSchedule
     */
    PhaseEnd?: string | null;
}


