/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 项目关联用户
 * @export
 * @interface ProjectUserInput
 */
export interface ProjectUserInput {
    /**
     * ProjectId
     * @type {number}
     * @memberof ProjectUserInput
     */
    ProjectId?: number;
    /**
     * 用户ids
     * @type {Array<number>}
     * @memberof ProjectUserInput
     */
    SysUserIds?: Array<number> | null;
}


