/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * MasterData-ProjectOverview
 * @export
 * @interface ProjectOverview
 */
export interface ProjectOverview {
    /**
     * 备用字段1
     * @type {string}
     * @memberof ProjectOverview
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof ProjectOverview
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof ProjectOverview
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof ProjectOverview
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof ProjectOverview
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof ProjectOverview
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof ProjectOverview
     */
    CreatorName?: string | null;
    /**
     * 主键Id
     * @type {number}
     * @memberof ProjectOverview
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverview
     */
    ProjectNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverview
     */
    ProjectCluster?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverview
     */
    ProjectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverview
     */
    ProjectManger?: string | null;
    /**
     * 来源于WorkLocation表
     * @type {string}
     * @memberof ProjectOverview
     */
    Location?: string | null;
    /**
     * 来源于CompanyInformation表
     * @type {string}
     * @memberof ProjectOverview
     */
    CompanyCode?: string | null;
    /**
     * 来源于币种字典 CNY,USD,JPY,EUR,GBP
     * @type {string}
     * @memberof ProjectOverview
     */
    LocalCurrency?: string | null;
}


