/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ProjectOverview输入模型
 * @export
 * @interface ProjectOverviewInput
 */
export interface ProjectOverviewInput {
    /**
     * Id主键
     * @type {number}
     * @memberof ProjectOverviewInput
     */
    ID?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    Location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    ProjectNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    ProjectManger?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    ProjectName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    ProjectCluster?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    CompanyCode?: string | null;
    /**
     * 备用字段1
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    Reserved1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectOverviewInput
     */
    LocalCurrency?: string | null;
}


