/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 查询类型枚举<br />&nbsp;等于 Equals = 0<br />&nbsp;不等于 NotEquals = 1<br />&nbsp;大于 GreaterThan = 2<br />&nbsp;大于等于 GreaterThanOrEquals = 3<br />&nbsp;小于 LessThan = 4<br />&nbsp;小于等于 LessThanOrEquals = 5<br />&nbsp;在列表中 StdIn = 6<br />&nbsp;不在列表中 StdNotIn = 7<br />&nbsp;包含 Contains = 8<br />&nbsp;不包含 NotContains = 9<br />&nbsp;头部包含 StartsWith = 10<br />&nbsp;尾部包含 EndsWith = 11<br />
 * @export
 * @enum {string}
 */

export enum QueryTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11
}



