/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { QueryConditionitem } from './query-conditionitem';

/**
 * 传入模型
 * @export
 * @interface QueryConditionTree
 */
export interface QueryConditionTree {
    /**
     * 传入模型
     * @type {Array<QueryConditionitem>}
     * @memberof QueryConditionTree
     */
    QueryConditionList?: Array<QueryConditionitem> | null;
}


