/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { QueryOptions } from './query-options';

/**
 * 查询表查询字段配置
 * @export
 * @interface QueryInput
 */
export interface QueryInput {
    /**
     * 字段名称
     * @type {string}
     * @memberof QueryInput
     */
    FieldName?: string | null;
    /**
     * 描述名称
     * @type {string}
     * @memberof QueryInput
     */
    DisplayName?: string | null;
    /**
     * 控件类型
     * @type {string}
     * @memberof QueryInput
     */
    ControlType?: string | null;
    /**
     * 值
     * @type {string}
     * @memberof QueryInput
     */
    Value?: string | null;
    /**
     * 数据来源
     * @type {string}
     * @memberof QueryInput
     */
    SourceData?: string | null;
    /**
     * 字典
     * @type {Array<QueryOptions>}
     * @memberof QueryInput
     */
    Options?: Array<QueryOptions> | null;
}


