/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 查询条件
 * @export
 * @interface QueryConditionitem
 */
export interface QueryConditionitem {
    /**
     * 字段名
     * @type {string}
     * @memberof QueryConditionitem
     */
    FieldName?: string | null;
    /**
     * 操作符(根据操作符判断是否条件组)
     * @type {string}
     * @memberof QueryConditionitem
     */
    Operator?: string | null;
    /**
     * 是否条件组
     * @type {boolean}
     * @memberof QueryConditionitem
     */
    IsGroup?: boolean;
    /**
     * 字段值
     * @type {any}
     * @memberof QueryConditionitem
     */
    Value?: any | null;
    /**
     * 
     * @type {Array<QueryConditionitem>}
     * @memberof QueryConditionitem
     */
    Children?: Array<QueryConditionitem> | null;
}


