/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * StaffingPlan
 * @export
 * @interface StaffingPlanInfo
 */
export interface StaffingPlanInfo {
    /**
     * 备用字段1
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    CreatorName?: string | null;
    /**
     * 主键Id
     * @type {number}
     * @memberof StaffingPlanInfo
     */
    ID?: number;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    ProjectNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    PositionCompanyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    CompanyCode?: string | null;
    /**
     * 来源于Discipline-MainDiscipline
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    MainDiscipline?: string | null;
    /**
     * 来源于Discipline-DisciplineWbs
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    DisciplineWbs?: string | null;
    /**
     * 来源于Discipline-SubDiscipline
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    SubDiscipline?: string | null;
    /**
     * 来源于staffPool的 EmployeeCode
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    EmployeeCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    FirstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    LastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    Function?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    OrgCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    OrgName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    WorkLocationCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    WorkLocationName?: string | null;
    /**
     * 来源于Project Master 下的Position
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    PositionName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    PositionCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    TypeOfPosition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    JobCategory?: string | null;
    /**
     * SurChargeRate
     * @type {number}
     * @memberof StaffingPlanInfo
     */
    SurChargeRate?: number | null;
    /**
     * LegalEntityProject
     * @type {string}
     * @memberof StaffingPlanInfo
     */
    LegalEntityProject?: string | null;
    /**
     * monthly working hours
     * @type {number}
     * @memberof StaffingPlanInfo
     */
    MonthlyWorkingHours?: number | null;
    /**
     * Project Monthly Rate
     * @type {number}
     * @memberof StaffingPlanInfo
     */
    ProjectMonthlyRate?: number | null;
    /**
     * Nr of Staffing per month
     * @type {number}
     * @memberof StaffingPlanInfo
     */
    NrOfStaffingPerMonth?: number | null;
}


