/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * StaffingPlanDetail
 * @export
 * @interface StaffingPlanDetail
 */
export interface StaffingPlanDetail {
    /**
     * 备用字段1
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    CreatorName?: string | null;
    /**
     * 主键Id
     * @type {number}
     * @memberof StaffingPlanDetail
     */
    ID?: number;
    /**
     * 主表id关联
     * @type {number}
     * @memberof StaffingPlanDetail
     */
    StaffingPlanId?: number;
    /**
     * 项目编号
     * @type {string}
     * @memberof StaffingPlanDetail
     */
    ProjectNo?: string | null;
    /**
     * 月份格式 YYYYMM
     * @type {number}
     * @memberof StaffingPlanDetail
     */
    Month?: number;
    /**
     * 月份数据
     * @type {number}
     * @memberof StaffingPlanDetail
     */
    MonthData?: number | null;
}


