/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 查询配置输入模型
 * @export
 * @interface SysQueryConditionOutput
 */
export interface SysQueryConditionOutput {
    /**
     * 备用字段1
     * @type {number}
     * @memberof SysQueryConditionOutput
     */
    ID?: number;
    /**
     * 备用字段1
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    CreatorName?: string | null;
    /**
     * 外键对应的配置Code
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    QueryConfigCode?: string | null;
    /**
     * 查询名称
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    Name?: string | null;
    /**
     * 查询字段配置
     * @type {string}
     * @memberof SysQueryConditionOutput
     */
    Content?: string | null;
}


