/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 授权角色权限输入
 * @export
 * @interface SysRolePermissionInput
 */
export interface SysRolePermissionInput {
    /**
     * 用户Id
     * @type {number}
     * @memberof SysRolePermissionInput
     */
    SysRoleId: number;
    /**
     * 权限集合
     * @type {Array<number>}
     * @memberof SysRolePermissionInput
     */
    PermissionIds?: Array<number> | null;
}


