/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { QueryInput } from './query-input';
import { QueryOutput } from './query-output';

/**
 * 查询配置输入模型
 * @export
 * @interface SysQueryConfigInput
 */
export interface SysQueryConfigInput {
    /**
     * 主键
     * @type {number}
     * @memberof SysQueryConfigInput
     */
    ID?: number;
    /**
     * 名称
     * @type {string}
     * @memberof SysQueryConfigInput
     */
    Name?: string | null;
    /**
     * 编码
     * @type {string}
     * @memberof SysQueryConfigInput
     */
    Code?: string | null;
    /**
     * 是否启用病区权限(默认无病区权限)
     * @type {boolean}
     * @memberof SysQueryConfigInput
     */
    IsEnableWardPermission?: boolean;
    /**
     * 是否显示(默认显示)
     * @type {boolean}
     * @memberof SysQueryConfigInput
     */
    IsShow?: boolean;
    /**
     * 描述
     * @type {string}
     * @memberof SysQueryConfigInput
     */
    Text?: string | null;
    /**
     * 来源表
     * @type {string}
     * @memberof SysQueryConfigInput
     */
    SourceTable?: string | null;
    /**
     * 查询字段配置
     * @type {Array<QueryInput>}
     * @memberof SysQueryConfigInput
     */
    InputList?: Array<QueryInput> | null;
    /**
     * 输出字段配置
     * @type {Array<QueryOutput>}
     * @memberof SysQueryConfigInput
     */
    OutputList?: Array<QueryOutput> | null;
}


