/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户项目表
 * @export
 * @interface SysUserProject
 */
export interface SysUserProject {
    /**
     * 备用字段1
     * @type {string}
     * @memberof SysUserProject
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysUserProject
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof SysUserProject
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysUserProject
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysUserProject
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof SysUserProject
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysUserProject
     */
    CreatorName?: string | null;
    /**
     * 主键Id
     * @type {number}
     * @memberof SysUserProject
     */
    ID?: number;
    /**
     * 用户Id
     * @type {number}
     * @memberof SysUserProject
     */
    SysUserId?: number;
    /**
     * 系统项目Id,来源于ProjectOverview表
     * @type {number}
     * @memberof SysUserProject
     */
    ProjectId?: number;
}


