/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CommonStatus } from './common-status';
import { SysPermissionOutput } from './sys-permission-output';

/**
 * 角色输出表
 * @export
 * @interface SysRoleOutput
 */
export interface SysRoleOutput {
    /**
     * ID
     * @type {number}
     * @memberof SysRoleOutput
     */
    ID?: number;
    /**
     * 备用字段1
     * @type {string}
     * @memberof SysRoleOutput
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysRoleOutput
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof SysRoleOutput
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysRoleOutput
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysRoleOutput
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof SysRoleOutput
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysRoleOutput
     */
    CreatorName?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof SysRoleOutput
     */
    Name: string;
    /**
     * 编码
     * @type {string}
     * @memberof SysRoleOutput
     */
    Code: string;
    /**
     * 排序
     * @type {number}
     * @memberof SysRoleOutput
     */
    Sort?: number;
    /**
     * 备注
     * @type {string}
     * @memberof SysRoleOutput
     */
    Remark?: string | null;
    /**
     * 菜单json
     * @type {string}
     * @memberof SysRoleOutput
     */
    MenuJson?: string | null;
    /**
     * 角色对应的权限
     * @type {Array<SysPermissionOutput>}
     * @memberof SysRoleOutput
     */
    Permissions?: Array<SysPermissionOutput> | null;
    /**
     * 
     * @type {CommonStatus}
     * @memberof SysRoleOutput
     */
    Status?: CommonStatus;
}


