/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NoticeStatus } from './notice-status';
import { NoticeType } from './notice-type';
import { NoticeUserRead } from './notice-user-read';

/**
 * 系统通知公告详情参数
 * @export
 * @interface SysNoticeDetailOutput
 */
export interface SysNoticeDetailOutput {
    /**
     * 主键
     * @type {number}
     * @memberof SysNoticeDetailOutput
     */
    ID?: number;
    /**
     * 标题
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    Title?: string | null;
    /**
     * 内容
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    Content?: string | null;
    /**
     * 
     * @type {NoticeType}
     * @memberof SysNoticeDetailOutput
     */
    Type?: NoticeType;
    /**
     * 发布人Id
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    PublicUserCode?: string | null;
    /**
     * 发布人姓名
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    PublicUserName?: string | null;
    /**
     * 发布时间
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    PublicTime?: string;
    /**
     * 撤回时间
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    CancelTime?: string;
    /**
     * 
     * @type {NoticeStatus}
     * @memberof SysNoticeDetailOutput
     */
    Status?: NoticeStatus;
    /**
     * 备用字段1
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof SysNoticeDetailOutput
     */
    CreatorName?: string | null;
    /**
     * 通知到的用户code集合
     * @type {Array<string>}
     * @memberof SysNoticeDetailOutput
     */
    NoticeUserCodeList?: Array<string> | null;
    /**
     * 通知到的用户阅读信息集合
     * @type {Array<NoticeUserRead>}
     * @memberof SysNoticeDetailOutput
     */
    NoticeUserReadInfoList?: Array<NoticeUserRead> | null;
}


