/* tslint:disable */
/* eslint-disable */
/**
 * 全部
 * 全部API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkLocation
 */
export interface WorkLocation {
    /**
     * 备用字段1
     * @type {string}
     * @memberof WorkLocation
     */
    Reserved1?: string | null;
    /**
     * 更新时间
     * @type {string}
     * @memberof WorkLocation
     */
    UpdatedTime?: string | null;
    /**
     * 修改者Id
     * @type {string}
     * @memberof WorkLocation
     */
    UpdatorCode?: string | null;
    /**
     * 修改者名称
     * @type {string}
     * @memberof WorkLocation
     */
    UpdatorName?: string | null;
    /**
     * 创建时间
     * @type {string}
     * @memberof WorkLocation
     */
    CreatedTime?: string | null;
    /**
     * 创建者Id
     * @type {string}
     * @memberof WorkLocation
     */
    CreatorCode?: string | null;
    /**
     * 创建者名称
     * @type {string}
     * @memberof WorkLocation
     */
    CreatorName?: string | null;
    /**
     * 主键Id
     * @type {number}
     * @memberof WorkLocation
     */
    ID?: number;
    /**
     * Country
     * @type {string}
     * @memberof WorkLocation
     */
    Country?: string | null;
    /**
     * WorkLocationCode
     * @type {string}
     * @memberof WorkLocation
     */
    WorkLocationCode?: string | null;
    /**
     * WorkLocationName
     * @type {string}
     * @memberof WorkLocation
     */
    WorkLocationName?: string | null;
}


